<?php

namespace AppBundle\Repository;

/**
 * Sent_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sent_listRepository extends \Doctrine\ORM\EntityRepository
{
}
